language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "308test3"
    token:
      secure: "81c7e6c9cc6f722d125aefe72cb93377974250d7"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
